//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeBianGu.Control.Dock.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeBianGu.Control.Dock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active Files 的本地化字符串。
        /// </summary>
        public static string Active_Files {
            get {
                return ResourceManager.GetString("Active_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Tool Windows 的本地化字符串。
        /// </summary>
        public static string Active_ToolWindows {
            get {
                return ResourceManager.GetString("Active_ToolWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Hide 的本地化字符串。
        /// </summary>
        public static string Anchorable_AutoHide {
            get {
                return ResourceManager.GetString("Anchorable_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Hide 的本地化字符串。
        /// </summary>
        public static string Anchorable_BtnAutoHide_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnAutoHide_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string Anchorable_BtnClose_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnClose_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Position 的本地化字符串。
        /// </summary>
        public static string Anchorable_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Anchorable_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock 的本地化字符串。
        /// </summary>
        public static string Anchorable_Dock {
            get {
                return ResourceManager.GetString("Anchorable_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock as Tabbed Document 的本地化字符串。
        /// </summary>
        public static string Anchorable_DockAsDocument {
            get {
                return ResourceManager.GetString("Anchorable_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string Anchorable_Float {
            get {
                return ResourceManager.GetString("Anchorable_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string Anchorable_Hide {
            get {
                return ResourceManager.GetString("Anchorable_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Pin status 的本地化字符串。
        /// </summary>
        public static string Document_BtnPinned_Hint {
            get {
                return ResourceManager.GetString("Document_BtnPinned_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Document_Close {
            get {
                return ResourceManager.GetString("Document_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All 的本地化字符串。
        /// </summary>
        public static string Document_CloseAll {
            get {
                return ResourceManager.GetString("Document_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All But This 的本地化字符串。
        /// </summary>
        public static string Document_CloseAllButThis {
            get {
                return ResourceManager.GetString("Document_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Position 的本地化字符串。
        /// </summary>
        public static string Document_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Document_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock as Tabbed Document 的本地化字符串。
        /// </summary>
        public static string Document_DockAsDocument {
            get {
                return ResourceManager.GetString("Document_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string Document_Float {
            get {
                return ResourceManager.GetString("Document_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move To Next Tab Group 的本地化字符串。
        /// </summary>
        public static string Document_MoveToNextTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToNextTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move To Previous Tab Group 的本地化字符串。
        /// </summary>
        public static string Document_MoveToPreviousTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToPreviousTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Horizontal Tab Group 的本地化字符串。
        /// </summary>
        public static string Document_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewHorizontalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Vertical Tab Group 的本地化字符串。
        /// </summary>
        public static string Document_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewVerticalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        public static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}
