// <auto-generated />
using System;
using HeBianGu.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeBianGu.DataBase.Sqlite.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("HeBianGu.Systems.Identity.hi_dd_author", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_code")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author_name")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("hi_dd_authors");
                });

            modelBuilder.Entity("HeBianGu.Systems.Identity.hi_dd_role", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_code")
                        .HasColumnOrder(2);

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("hi_dd_roles");
                });

            modelBuilder.Entity("HeBianGu.Systems.Identity.hi_dd_user", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display")
                        .HasColumnOrder(4);

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name")
                        .HasColumnOrder(1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password")
                        .HasColumnOrder(3);

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("hi_dd_users");
                });

            modelBuilder.Entity("HeBianGu.Systems.Logger.hl_dm_debug", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value")
                        .HasColumnOrder(4);

                    b.HasKey("ID");

                    b.ToTable("hl_dm_debugs");
                });

            modelBuilder.Entity("HeBianGu.Systems.Logger.hl_dm_error", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("excetion")
                        .HasColumnOrder(5);

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Parameter")
                        .HasColumnType("TEXT")
                        .HasColumnName("parameter")
                        .HasColumnOrder(3);

                    b.Property<string>("Stack")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("hl_dm_errors");
                });

            modelBuilder.Entity("HeBianGu.Systems.Logger.hl_dm_fatal", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("excetion")
                        .HasColumnOrder(5);

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Parameter")
                        .HasColumnType("TEXT")
                        .HasColumnName("parameter")
                        .HasColumnOrder(3);

                    b.Property<string>("Process")
                        .HasColumnType("TEXT")
                        .HasColumnName("process")
                        .HasColumnOrder(8);

                    b.Property<string>("Stack")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack")
                        .HasColumnOrder(6);

                    b.Property<string>("System")
                        .HasColumnType("TEXT")
                        .HasColumnName("system")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("hl_dm_fatals");
                });

            modelBuilder.Entity("HeBianGu.Systems.Logger.hl_dm_info", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value")
                        .HasColumnOrder(4);

                    b.HasKey("ID");

                    b.ToTable("hl_dm_infos");
                });

            modelBuilder.Entity("HeBianGu.Systems.Logger.hl_dm_warn", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value")
                        .HasColumnOrder(4);

                    b.HasKey("ID");

                    b.ToTable("hl_dm_warns");
                });

            modelBuilder.Entity("HeBianGu.Systems.Operation.hi_dd_operation", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISENBLED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("hi_dd_operations");
                });

            modelBuilder.Entity("hi_dd_authorhi_dd_role", b =>
                {
                    b.Property<string>("AuthorsID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesID")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorsID", "RolesID");

                    b.HasIndex("RolesID");

                    b.ToTable("hi_dd_authorhi_dd_role");
                });

            modelBuilder.Entity("HeBianGu.Systems.Identity.hi_dd_user", b =>
                {
                    b.HasOne("HeBianGu.Systems.Identity.hi_dd_role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("hi_dd_authorhi_dd_role", b =>
                {
                    b.HasOne("HeBianGu.Systems.Identity.hi_dd_author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeBianGu.Systems.Identity.hi_dd_role", null)
                        .WithMany()
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeBianGu.Systems.Identity.hi_dd_role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
